show_on_mobile:
  default: true
  description: 'Show tag banners on mobile devices'

show_tag_description:
  default: true
  description: 'Show tag description when available'

show_above_site_header:
  default: false
  type: bool
  description: 'Display the banner in the above site header connector.'

show_below_site_header:
  default: true
  type: bool
  description: 'Display the banner in the below site header connector.'

remove_tag_hyphen:
  default: false
  type: bool
  description: 'Remove hyphens from tag names in banners'

remove_tag_underscore:
  default: false
  type: bool
  description: 'Remove underscores from tag names in banners'
